### PR TITLE
21 better parser

### LINKED ISSUE #21: make the parser and lexer more error resilient
The [lexer] and [parser], use a dumb diagnostic handling method, they return a `Result<T, Diagnostic>` and pratically never use `self.diags.emit(DIAGNOSTIC)`, that is the better approach because it permits us to emit more diagnostics in one file, for example we have a lot of `E006` kind of testing file, because we can't put two of those errors and still both be emitted.

For the lexer this is very simple to change, we stop returning Diags we emit them and we used dummy values when we need a value to be computed.

For the parser, it's a bit more complex because the current `expect_token!` and `parse!` macros cannot work simply with this, and we will need to (partially) reimplement a parser using simple methods like `next_token`, `next_tt`, `consume_token` etc... So there is more work than for the lexer. While doing that, it may be a good idea to point the diag of expecting a `;` after a statement one character after the last token to be a little more accurate.

Also create the `Spanned<T>` like:
```rust
// some derives..
pub struct Spanned<T> {
     node: T,
     loc: Span,
}
```
And replace the `SpannedPath` by `Spanned<Path>`

And so we need to remove `Result`s everywhere in the compiler and not only in the parser and the lexer.

While doing that, add a new flag named `-Zdiag-debug=<bool>`, if enabled, all diagnostics rendered will have an additional note saying `DEBUG: this diagnostic was emited in <file>, at <LINE>:<COLUMN>`. (use the track_caller mechanism of rust).

[lexer]: https://github.com/lunprog/lun/tree/main/compiler/lunc_lexer
[parser]: https://github.com/lunprog/lun/tree/main/compiler/lunc_parser

### PR DESCRIPTION
**Pull request by thi8v**
This PR implements, and closes #21.

### CODE REVIEW

**Comment by thi8v** [comment]
maybe `ExpToken` is redundant? we could just use TokenRepr (and rename it to TokenExp) when we want to expect/check a token that has a value (or not) we check that the discriminants are equal (`TokenType::Ident(..) == TokenExp::Ident -> true` etc..) needs to create a test to ensure the discriminant of `TokenType::LParen == TokenExp::LParen` etc for all token types, the only drawback is that token types will need to be synced.

Like that, token without a value work fine.

And token with values (like ident or literals), if everything went well, the token is now in `Parser::prev_token`, so we could make helper methods like `Parser::token_as_lit(&self) -> Option<Lit>`, and `Parser::token_as_ident(&self) -> Option<String>`.

**Comment by thi8v** [comment]
Remove all the `Expr::*Lit` ast nodes and replace them by `Expr::Lit(Lit)`, also do it in subsequent stages, DSIR and SCIR.

**Comment by thi8v** [comment]
Remove the bool type in the ast by a type with it's own name, like:

```rust
pub enum Mutable {
    Yes,
    No,
}
```

**Comment by thi8v** [comment]
Change the way Diagnostic Helper structs (`ExpectedToken` for example) gets converted to `Diagnostic`, because with the new way diagnostics can be handled, we are not always emitting where we are creating the diagnostic, so the trait `IntoDiagnostic` should have access to the `DiagnosticSink` soi that it can embed the debug information as soon as the macro is called. A new method should be created, `sink.create_diag(DIAGNOSTIC_HELPER)`, it just calls the `into_diag` with the `sink`. The `IntoDiagnostic` trait should be renamed to `DiagHelper`.

File: compiler/lunc_parser/src/lib.rs [hunk 1]
```diff
@@ -23,72 +26,274 @@ pub mod item;
...
+    #[deprecated(note = "it's useless.")]
+    pub(crate) fn eof_diag(&self) -> Diagnostic {
+        let eof = self.tokstream.get_eof();
+        ReachedEOF {
+            loc: eof.loc.clone(),
+        }
+        .into_diag()
+    }
+
+    // until here.
```
Comment (thi8v) [inline compiler/lunc_parser/src/lib.rs]: **TODO: don't forget to remove after the whole rewrite.**

File: compiler/lunc_parser/src/lib.rs
Comment (thi8v) [inline compiler/lunc_parser/src/lib.rs]: **TODO: don't forget to also remove that after rewrite**

File: compiler/lunc_parser/src/lib.rs [hunk 2]
```diff
@@ -127,6 +319,16 @@ pub trait AstNode: Debug + PrettyDump {
         Self: Sized;
 }
```
Comment (thi8v) [inline compiler/lunc_parser/src/lib.rs]: **TODO: Also remove that**

**Comment by thi8v** [comment]
for maximum resilience in the parsing of expr, stmt and item, everywhere there is a bunch of paths like that, we could try to re-parse after bumping the parser while still emitting diags, but in this mode of `parsing after bumping` we record the diags. If there are errors we go back to where we were before this `parsing after bumping` and don't emit those diags, but if the `parsing after bumping` succeeded we keep the result.

**Comment by thi8v** [comment]
in every stage of the compiler move this part of `produce`:
```rust
if self.sink.failed() {
    return None;
}
```
in the driver, so that the compiler can display the result of the stages and also the diagnostics, all in one.

**Comment by thi8v** [comment]
> Change the way Diagnostic Helper structs (`ExpectedToken` for example) gets converted to `Diagnostic`, because with the new way diagnostics can be handled, we are not always emitting where we are creating the diagnostic, so the trait `IntoDiagnostic` should have access to the `DiagnosticSink` soi that it can embed the debug information as soon as the macro is called. A new method should be created, `sink.create_diag(DIAGNOSTIC_HELPER)`, it just calls the `into_diag` with the `sink`. The `IntoDiagnostic` trait should be renamed to `DiagHelper`.

out of the scope of this pr. opened an issue

**Comment by thi8v** [comment]
lgtm, everything in the scope of this PR / #21 was implemented.
